# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "cosnix-tf-dev"
    credentials = "/Users/ravindranathyadav/Downloads/dev-project-409209-3edbe624b393.json"
    prefix      = "./terraform.tfstate"
  }
}
