# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
    region = "us-east-1"
    project = "dev-project-409209"
    default_labels = {
      managed_by = "terraform"
      environment = "dev"
  }
}
